[package]
edition = "2021"             # Allowed values are 2015, 2018, 2021
name    = "svc-scheduler"
version = "0.2.5-develop.12"
# Rust Editions: https://doc.rust-lang.org/edition-guide/index.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vendored-openssl = ['openssl/vendored']

[dependencies]
async-trait      = "0.1"
cargo-husky      = "1"
chrono           = "0.4"
chrono-tz        = "0.8"
dotenv           = "0.15"
env_logger       = "0.10"
iso8601-duration = "0.1"
log              = "0.4"
log4rs           = "1.2"
once_cell        = "1.15"
openssl          = "0.10"
ordered-float    = "3.2"
prost            = "0.11"
prost-types      = "0.11"
rrule            = "0.10"
tokio            = { version = "1.20", features = ["full"] }
tonic            = "0.8"
tonic-health     = "0.8"
uuid             = "1.2"

[dependencies.router]
branch = "develop"
git    = "https://github.com/Arrow-air/lib-router.git"

[dependencies.svc-compliance-client-grpc]
branch = "develop"
git    = "https://github.com/Arrow-air/svc-compliance.git"

[dependencies.svc-storage-client-grpc]
git = "https://github.com/Arrow-air/svc-storage.git"
tag = "v0.9.0-develop.14"

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies]
serial_test = "1.0.0"

[dev-dependencies.cargo-husky]
default-features = false          # Disable features which are enabled by default
features         = ["user-hooks"]
version          = "1"

[[bin]]
name = "svc-scheduler"
src  = "src/main.rs"
