[package]
edition = "2021"            # Allowed values are 2015, 2018, 2021
name    = "svc-scheduler"
version = "0.2.5-develop.3"
# Rust Editions: https://doc.rust-lang.org/edition-guide/index.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vendored-openssl = ['openssl/vendored']

[dependencies]
cargo-husky             = "1"
chrono                  = "0.4"
chrono-tz               = "0.6"
dotenv                  = "0.15"
env_logger              = "0.9"
iso8601-duration        = "0.1"
log                     = "0.4"
log4rs                  = "1.2"
once_cell               = "1.15"
openssl                 = "0.10"
ordered-float           = "3.2"
prost                   = "0.11"
prost-types             = "0.11"
router                  = { path = "../../lib-router" }
rrule                   = "0.10"
svc-storage-client-grpc = { path = "../../svc-storage/client-grpc" }
tokio                   = { version = "1.20", features = ["full"] }
tonic                   = "0.8"
tonic-health            = "0.7"
uuid                    = "1.2"
async-trait             = "0.1"

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies]
tempfile = "3.3.0"
tower = { version = "0.4" }
tokio-stream = { version = "0.1.8", features = ["net"] }

[dev-dependencies.cargo-husky]
default-features = false          # Disable features which are enabled by default
features         = ["user-hooks"]
version          = "1"

[[bin]]
name = "svc-scheduler"
src  = "src/main.rs"
