[package]
description = "GRPC client for the scheduler service."
name        = "svc-scheduler-client-grpc"
version     = "0.2.5-develop.16"

categories.workspace   = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license-file.workspace = true
repository.workspace   = true

# See more keys and their definitions at https://doc.rust-lang.org/scheduler/reference/manifest.html

[dependencies]
chrono      = "0.4"
chrono-tz   = "0.8"
prost       = "0.11"
prost-types = "0.11"
tonic       = "0.8"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[lib]
name = "svc_scheduler_client_grpc"
path = "src/lib.rs"

[[example]]
name = "grpc"
