[package]
edition = "2021"
name    = "svc-scheduler-client-grpc"
version = "0.2.4-develop.0"

# See more keys and their definitions at https://doc.rust-lang.org/scheduler/reference/manifest.html

[dependencies]
chrono      = "0.4.22"
chrono-tz   = "0.8.0"
prost       = "0.11.0"
prost-types = "0.11.1"
tonic       = "0.8.1"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[lib]
name = "svc_scheduler_client_grpc"
path = "src/lib.rs"

[[example]]
name = "grpc"
